### ISSUE TITLE
Several issues 

### ISSUE THREAD

**Issue by bbukovic** [giohappy/gdal2cesium#4]
Hi,

I have observed two minor things:
- there is a "which" command used. This does not work on Windows OS. One should replace it with "where" command to run the script on windows machine.

- running script with the following command does not work on Windows machine - at least not in my case:
gdal2cesium.py -o tiles *.tiff
The same command is shown as an example of usage.
I get an error: gdal2cesium.py: error: It is not possible to open the input file '*.tif'.

This is simple to overcome, just list the filenames instead of using "*.tif", e.g.:
gdal2cesium.py -o tiles file1.tif file2.tif file3.tif

And then I have two more issues:
- the first one is: when I run the gdal2cesium.py I get the following error:
gdal2cesium.py -o tiles IDW_A23.tif
Processing: IDW_A23.tif
Traceback (most recent call last):
  File "D:\gdal2cesium\d48_output2\gdal2cesium.py", line 934, in <module>
    gdal2cesium.process()
  File "D:\gdal2cesium\d48_output2\gdal2cesium.py", line 142, in process
    self.make_tiles()
  File "D:\gdal2cesium\d48_output2\gdal2cesium.py", line 561, in make_tiles
    self.vrts[vrt_file][1] = tz-1
KeyError: None

Ok, I have not digged into the logic and I just added one more if clause to check whether script generates some output or not. Now this block of the code looks like this in my script:
if res != tmp_res:
    if tz < self.tmaxz:
        if vrt_file is not None:
            self.vrts[vrt_file][1] = tz-1
    tmp_res = res
    self.make_vrt(res,i)
    vrt_file = "cesium_%s.vrt" % i
    self.vrts[vrt_file] = [tz,None]
    i += 1

After this change the script generated terrain tiles. Here comes the second issue that I do not know how to overcome and its source can be my source code change:
- I run the script to generate terrain tiles from 90 tif files. All tif files have been processed with no errors. After putting terrain in cesium viewer only 1/4 of terrain is build properly obviously. Now I am not sure whether this is cesium or gdal2cesium script problem (or even source tif files). I have noticed that moving around flattened area no request for terrain is made in web browser, so I assume that terrain is not generated there at all.
I have also tried to generate terrain for different areas of the country and always only 1/3 - 1/4 of the area is generated.
Maybe it is something wrong with the part of source code I have changed (added if clause), but this was the only way to successfully run the script.

This is terrain loaded in cesium where the border between generated and not generated can be seen:
![cesium_sc](https://cloud.githubusercontent.com/assets/7601405/5354351/14f7e2f6-7f87-11e4-890e-ca2f667acadd.PNG)

Regards

**Comment by giohappy** [comment]
Hi,
I'm sorry but the latest notification was trashed by my email system, and I didn't receive it. Could you reactivate the download links?

**Comment by bbukovic** [comment]
Hi,

Below are new links where you will find source tif files and output generated on my machine.

- source files:
https://www.dropbox.com/s/9cd8be2ugp0xc0z/abcd_source_tiff_files.zip?dl=0

- terrain output (index shape file is also included):
https://www.dropbox.com/s/a12ihrkhypwos97/my_output_tiles.zip?dl=0

Thank you!

**Comment by giohappy** [comment]
Thanks, I'm downloading them. I'll let you know as soon as I can give them a look.

**Comment by giohappy** [comment]
@bbukovic I've spot the error. I will work on it as soon as possible. Thanks ;)

**Comment by giohappy** [comment]
It should be fixed now. Can you try it?

**Comment by bbukovic** [comment]
That was fast :) And I am very glad I can confirm that it works like a charm. Thank you very much!
