### ISSUE TITLE
OSGeo4W Shell Result

### ISSUE THREAD

**Issue by webmap2015** [giohappy/gdal2cesium#5]
I downloaded "SRTM_1km.tif" from "http://srtm.csi.cgiar.org/" link and copy gdal2cesium.py to 

OSGeo4W  path. Run the OSGeo4W. The result:

                   -={ OSGeo4W Shell Commands }=-

       bmp2tiff           geotifcp           ras2tiff
       cs2cs              gif2tiff           raw2tiff
       curl               gltpd              rgb2ycbcr
       dllupdate          listgeo            rpcgen
       example1           nad2bin            testepsg
       example2           nccopy             textreplace
       fax2ps             ncdump             thumbnail
       fax2tiff           ncgen              tiff2bw
       gdaladdo           ncgen3             tiff2pdf
       gdalbuildvrt       nearblack          tiff2ps
       gdaldem            nircmd             tiff2rgba
       gdalenhance        nircmdc            tiffcmp
       gdalinfo           ogdi_import        tiffcp
       gdallocationinfo   ogdi_info          tiffcrop
       gdalmanage         ogr2ogr            tiffdither
       gdalserver         ogrinfo            tiffdump
       gdalsrsinfo        ogrlineref         tiffinfo
       gdaltindex         ogrtindex          tiffmedian
       gdaltransform      osgeo4w-setup      tiffset
       gdalwarp           pal2rgb            tiffsplit
       gdal_contour       ppm2tiff           xmlcatalog
       gdal_grid          proj               xmllint
       gdal_rasterize     psql               xmlwf
       gdal_translate     python             xxmklink
       geod               pythonw

       epsg_tr           gdalimport        make-bat-for-py
       esri2wkt          gdalmove          mkgraticule
       gcps2vec          gdal_auth         o-help
       gcps2wld          gdal_calc         o4w_env
       gdal2cesium       gdal_edit         pct2rgb
       gdal2tiles        gdal_fillnodata   rgb2pct
       gdal2tilesTMSNo   gdal_merge        setup-test
       gdal2xyz          gdal_polygonize   setup
       gdalchksum        gdal_proximity
       gdalcompare       gdal_retile
       gdalident         gdal_sieve

GDAL 1.11.2, released 2015/02/10

C:\>gdal2cesium -o tiles SRTM_1km.tif
'which' is not recognized as an internal or external command, operable program or batch file.
gdalbuildvrt is required to run gdal2cesium in multi inumpyuts mode

C:\>

**Comment by giohappy** [comment]
I never tried on Windows. I will fix it asap, in the meanwhile you can comment lines from 318 to 322 (prepand each line with an asterisk "#")

**Comment by Akimh** [comment]
Hello,
How do you implement/copy the gdal2cesium.py into osgeo4w? 
Thank you!

**Comment by webmap2015** [comment]
![test](https://cloud.githubusercontent.com/assets/10267317/8065325/72c3bc42-0ee9-11e5-9c48-79ba55e3a152.png)

**Comment by Akimh** [comment]
Thank you. I implemented it but it throws another error:

![capture](https://cloud.githubusercontent.com/assets/12158315/8065859/abac2340-0e90-11e5-8fbf-ed1fa9dabbe5.JPG)

**Comment by webmap2015** [comment]
You need to install "shapely" packet in OSGeo4W setup
![untitled](https://cloud.githubusercontent.com/assets/10267317/8094202/2d67d4ae-0fce-11e5-8acb-cc1f9fc8313e.png)

**Comment by Akimh** [comment]
webmap2015, 
thanks a lot for your great support. 
I got the tool running and it created  the tile directory. But I got another error message after the tiling process.

![capture](https://cloud.githubusercontent.com/assets/12158315/8113806/d0cfb5a0-101c-11e5-8718-dd3c512801ae.JPG)

**Comment by giohappy** [comment]
Hi Akimh, I'm out of office until the end of June and I cannot do testing. Are you working with a WGS84 raster?

**Comment by Akimh** [comment]
Hi giohappy, thanks for your response. 
Before I used your tool, I warped the raster like in your example (UTM to WGS 84 and nodata to 0).
I deleted also the code lines you recommended.
Thank you.

**Comment by giohappy** [comment]
I'm sorry I cannot test it right know. I will do it, with your data, asap
(end of June I suspect)
Il 12/giu/2015 11:28, "Akimh" <notifications@github.com> ha scritto:

**Comment by Akimh** [comment]
No problem, thanks for your support (also from webmap2015).

**Comment by jhpoosthoek** [comment]
Dear all, I encountered a similar issue and was wondering what the current status is? I'm trying to show elevation data from the planet Mars in Cesium.

**Comment by Akimh** [comment]
I'm still interested too  since I didn't hear from giohappy yet.

**Comment by giohappy** [comment]
Hi all,
I'm back from a long, foreign, travel. I'm on holidays now but I will give
it a look asap.
Stay tuned,
giovanni

2015-08-03 20:26 GMT+02:00 Akimh <notifications@github.com>:

> I'm still interested too since I didn't hear from giohappy yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giohappy/gdal2cesium/issues/5#issuecomment-127362292>.
>



-- 
Giovanni Allegri
http://about.me/giovanniallegri
Gis3W - http://gis3w.it
Ikare - http://ikare.it
Twitter: https://twitter.com/_giohappy_
blog: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus

**Comment by giohappy** [comment]
I'm downloading the same data to reproduce the error. Are you both working on Windows?

**Comment by giohappy** [comment]
Probably gdal2cesium will exit with an error at the end of the post processing phase. It happens on Windows only, and I don't have the time to investigate it. I work on Linux, sorry.
PS: for SRTM data remember to set nodata value to 0

**Comment by Akimh** [comment]
No problem . Thanks anyways.

**Comment by jhpoosthoek** [comment]
Also not a problem, thanks for checking.

**Comment by giohappy** [comment]
Hei, as you can see I've fixed the issues. Let me know.
Il 04/ago/2015 23:05, "Jelmer Oosthoek" <notifications@github.com> ha
scritto:

**Comment by jhpoosthoek** [comment]
I hope to find time to test it soon. Thanks for fixing!
